[package]
name = "fastdi-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "fastdi_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module"] }
once_cell = "1"

